microservice:
  payment-service-app:
    endpoints:
      endpoint:
        url: http://localhost:8082/payments/doPayment
  order-service-app:
    endpoints:
      endpoint:
        url: http://localhost:8081/orders/bookOrder
