microservice:
  payment-service-app:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE-APP/payments/doPayment
  order-service-app:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE-APP/orders/bookOrder
